name: ci 
on:
  push:
    branches:
      - docs

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-pdf-export-plugin mkpdfs-mkdocs mkdocs mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
      - run: cd docs && mkdocs gh-deploy --force


